-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  jwt_tokens

CREATE TABLE IF NOT EXISTS jwt_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jti CHAR(36) NOT NULL UNIQUE,
  user_id BIGINT NULL,
  token_hash BYTEA NOT NULL,
  token_hash_algo VARCHAR(50) NULL,
  token_hash_key_version VARCHAR(64) NULL,
  type TEXT NOT NULL DEFAULT 'refresh',
  scopes VARCHAR(255) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT chk_jwt_tokens_version CHECK (version >= 0),
  expires_at TIMESTAMPTZ(6) NULL,
  last_used_at TIMESTAMPTZ(6) NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  replaced_by BIGINT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  meta JSONB NULL,
  CONSTRAINT uq_jwt_token_hash UNIQUE (token_hash),
  CONSTRAINT chk_jwt_type CHECK (type IN ('refresh','api')),
  CONSTRAINT chk_jwt_expires_after_created CHECK (expires_at IS NULL OR expires_at >= created_at)
);
